REM INSERTING into EXPORT_TABLE
SET DEFINE OFF;
Insert into EXPORT_TABLE (CLASS,YEAR,PERIOD_NUM) values ('ICS4U-01',2018,1);
Insert into EXPORT_TABLE (CLASS,YEAR,PERIOD_NUM) values ('ICS4U-02',2018,2);
Insert into EXPORT_TABLE (CLASS,YEAR,PERIOD_NUM) values ('ICS4U-03',2018,3);
Insert into EXPORT_TABLE (CLASS,YEAR,PERIOD_NUM) values ('ICS4U-04',2018,4);
Insert into EXPORT_TABLE (CLASS,YEAR,PERIOD_NUM) values ('ICS4U-05',2018,1);
Insert into EXPORT_TABLE (CLASS,YEAR,PERIOD_NUM) values ('ICS4U-06',2018,2);
Insert into EXPORT_TABLE (CLASS,YEAR,PERIOD_NUM) values ('ICS4U-07',2018,3);
Insert into EXPORT_TABLE (CLASS,YEAR,PERIOD_NUM) values ('ICS4U-08',2018,4);
Insert into EXPORT_TABLE (CLASS,YEAR,PERIOD_NUM) values ('ICS4U-01',2019,1);
Insert into EXPORT_TABLE (CLASS,YEAR,PERIOD_NUM) values ('ICS4U-02',2019,2);
