--------------------------------------------------------
--  File created - Thursday-December-27-2018   
--------------------------------------------------------
REM INSERTING into EOM.EOM_STUDENTS
SET DEFINE OFF;
Insert into EOM.EOM_STUDENTS (STUDENT_ID,CLASS,FIRST_NAME,LAST_NAME,SORT_ID) values (1,'ICS4U-01/2018','Mike','Dong',5);
Insert into EOM.EOM_STUDENTS (STUDENT_ID,CLASS,FIRST_NAME,LAST_NAME,SORT_ID) values (2,'ICS4U-01/2018','Siddharth','Natamai',11);
Insert into EOM.EOM_STUDENTS (STUDENT_ID,CLASS,FIRST_NAME,LAST_NAME,SORT_ID) values (3,'ICS4U-02/2018','Wade','Huang',14);
Insert into EOM.EOM_STUDENTS (STUDENT_ID,CLASS,FIRST_NAME,LAST_NAME,SORT_ID) values (4,'ICS4U-01/2018','Robert ','Anca',1);
Insert into EOM.EOM_STUDENTS (STUDENT_ID,CLASS,FIRST_NAME,LAST_NAME,SORT_ID) values (5,'ICS4U-01/2018','Ojas','Bhatia',2);
Insert into EOM.EOM_STUDENTS (STUDENT_ID,CLASS,FIRST_NAME,LAST_NAME,SORT_ID) values (6,'ICS4U-01/2018','Bilal','Chaudhry',3);
Insert into EOM.EOM_STUDENTS (STUDENT_ID,CLASS,FIRST_NAME,LAST_NAME,SORT_ID) values (7,'ICS4U-01/2018','Evan','Chu',4);
Insert into EOM.EOM_STUDENTS (STUDENT_ID,CLASS,FIRST_NAME,LAST_NAME,SORT_ID) values (8,'ICS4U-01/2018','Matthew','Hobbs',6);
Insert into EOM.EOM_STUDENTS (STUDENT_ID,CLASS,FIRST_NAME,LAST_NAME,SORT_ID) values (9,'ICS4U-01/2018','Aumio','Islam',7);
Insert into EOM.EOM_STUDENTS (STUDENT_ID,CLASS,FIRST_NAME,LAST_NAME,SORT_ID) values (10,'ICS4U-01/2018','Mohamed','Kaddour',8);
Insert into EOM.EOM_STUDENTS (STUDENT_ID,CLASS,FIRST_NAME,LAST_NAME,SORT_ID) values (11,'ICS4U-01/2018','Anuj','Radia',13);
Insert into EOM.EOM_STUDENTS (STUDENT_ID,CLASS,FIRST_NAME,LAST_NAME,SORT_ID) values (12,'ICS4U-01/2018','Adam','Koziak',9);
Insert into EOM.EOM_STUDENTS (STUDENT_ID,CLASS,FIRST_NAME,LAST_NAME,SORT_ID) values (13,'ICS4U-01/2018','Kousha','Motezedian',10);
Insert into EOM.EOM_STUDENTS (STUDENT_ID,CLASS,FIRST_NAME,LAST_NAME,SORT_ID) values (22,'ICS4U-01/2018','Soumya','Natamai',12);
